apiVersion: v1
kind: Service  #Xác định loại kubernetes object, Ví dụ : Deployment, services, Job
metadata:
  name: backend
spec:
  selector: #Selector xác định object mà Service này sẽ điều khiển, Ở đây là pod
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080  # APP run ở cổng 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment #Xác định loại kubernetes object, Ví dụ : Deployment, services, Job
metadata:
  name: second-app-deployment # tên của kubernetes Object, Ở đây là tên của Deployment
spec:  # Viết tắt của Specification
  replicas: 3
  selector:
    matchLabels: # Xác định Pod nào sẽ đc điều khiển
      app: second-app
  template:    #Pod
    metadata:
      labels:
        app: second-app #Tên node là Second-app
    spec:    #Containers
      containers:
        - name: second-node
          image: 123497/kub-first-app:2





