apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc # Tên PersistentVolumeClaim
spec:
  volumeName: host-pv #Tên của PersistentVolume cần Claim
  accessModes:
    - ReadWriteOnce #Mode để claim
  storageClassName: standard # Gõ `kubectl get sc` để biết storage trong k8s
  resources:
    requests:
      storage: 1Gi