apiVersion: v1
kind: PersistentVolume #Xác định loại kubernetes object, Ví dụ : Deployment, services, Job, PersistentVolume
metadata:
  name: host-pv #Tên của PersistentVolume
spec:  #Specification cho persistentVolume
  capacity: # Xác định dung lượng  bộ nhớ cần dùng cho nhiều pods
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard # Gõ `kubectl get sc` để biết storage trong k8s
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate